<?php

/**
 * @file
 * Install hooks for this module.
 */

/**
 * Implements hook_install().
 *
 * @see islandora_cwrc_writer_islandora_required_objects()
 */
function islandora_cwrc_writer_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  // Install required object(s).
  islandora_install_solution_pack('islandora_cwrc_writer');
}

/**
 * Implements hook_uninstall().
 */
function islandora_cwrc_writer_uninstall() {
  islandora_uninstall_solution_pack('islandora_cwrc_writer');
  $variables = array(
    'islandora_cwrc_writer_person_entity_collection',
    'islandora_cwrc_writer_organization_entity_collection',
    'islandora_cwrc_writer_title_entity_collection',
    'islandora_cwrc_writer_place_entity_collection',
  );
  foreach ($variables as $variable) {
    variable_del($variable);
  }
}
